# Introduction to **NumPy**

Until now, within Python, we have worked with the **SymPy** module, which allows us to handle symbolic calculus, define new functions, compute limits, or, as we will see later, differentiate and integrate functions.

However, Python's possibilities for mathematical computation do not end there, not by a long shot. We now turn our attention to a tool that turns Python into a kind of super-calculator, with enormous potential for carrying out large repetitive operations with numbers, vectors, or matrices. We will make the most of it when programming the numerical methods studied in this course, although of course its possibilities are much broader.

Getting straight to the point, we are going to introduce the **NumPy** library (http://www.numpy.org/), which is the most widely used for numerical computation. This library makes it possible to use an enormous range of data structures and functions for numerical calculations. In this section we will show some of these features.

**NumPy** is a huge library with extremely broad capabilities, so here we only aim to provide a very brief introduction. To discover new features and how to use it for many other purposes, the best online source of information is search engines and, in particular, the community at http://stackoverflow.com/.

## Objectives

- Work with objects and methods.
- Introduction to one-dimensional arrays of numbers (`numpy.array`).
- Apply elementary numerical operations.
- Manipulation of numerical arrays (indexing, slicing, *etc.*).
- Exercise: efficiency of **NumPy** in vectorized and non-vectorized functions.


**Importing the NumPy module**

First of all, in order to have **NumPy** available in the code, we must import it. To do this, it is customary to import **NumPy** using the alias `np`:


In [1]:
import numpy as np

## Object-oriented programming

Like all Python modules, the **NumPy** library is implemented following an object-oriented programming strategy. Therefore, any data structure in Python, even the simplest one, should be understood as an object belonging to a class, and we can perform on it all the operations implemented for that class of objects. Even a number is an object of a class:


In [2]:
a = 3.3
print(a)
print(type(a))
isinstance(a,float)

3.3
<class 'float'>


True

For example, to check the attributes and methods that we can apply to a particular object, we can use the `dir()` function, which returns a list with their names. As can be seen in the list, we can distinguish two types of attributes and methods: those with the prefix and suffix `__*__`, and those without. The first type are called **private** and usually refer to the most basic calculations that can be performed within the class to which the object belongs.


In [3]:
dir(a)

['__abs__',
 '__add__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getformat__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__le__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 'as_integer_ratio',
 'conjugate',
 'fromhex',
 'hex',
 'imag',
 'is_integer',
 'real']

For example, we can check whether one real number is greater than another in two different ways: by using the logical operator `>` or by using its private method `__ge__`:


In [4]:
a=6.4; b=5.3
print(a.__gt__(b))
print(a > b)

True
True


In any case, in Python both private and public methods are used in the same way. For example:


In [5]:
a=3.4
print(a.is_integer())
print(a.__int__())
print(int(a))

False
3
3


> **NOTE**: In this course we are not going to work with, nor will it be necessary to implement, code using object-oriented programming. But it will be necessary to be aware of when objects of different classes are being used and what attributes and methods are defined in each case.


## Arrays of numbers

In Python there are many ways to store numerical data (or not), such as the list or tuple structures. In particular, lists can contain a finite ordered sequence of numbers (and an index can be used to access each of the elements of the list). Moreover, they are flexible enough to contain data of different kinds (a combination of integers, real numbers, lists of lists, *etc.*).

But this flexibility of lists in Python makes their computational performance quite limited. In most scientific applications in mathematics (together with their applications to different parts of computer engineering, artificial intelligence, data science, ...), real problems need operations on huge data sets and, therefore, computational speed is very important. To work efficiently on these problems, **NumPy** provides specialized functions and suitable data structures. In particular, for collections of numbers of the same type (losing some of the flexibility of lists, but gaining computational efficiency).

**One-dimensional arrays**: A one-dimensional array is an ordered collection of numbers that can be accessed by index (thus preserving order). By default, **NumPy** arrays are row arrays.

**Creating arrays and indexing**: To create a **NumPy** array of length 10 initialized with zeros, we would use the `np.zeros()` function:


In [6]:
u = np.zeros(10)
print(u)
print(type(u))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


The default type of the numbers contained in **NumPy** arrays is `float64` (the type stored in `np.float`). If we want to use other types, we must use the optional argument `dtype`. The type of the numbers contained in an array can be checked by accessing the `dtype` attribute of **NumPy** arrays:


In [7]:
print(u.dtype)
w = np.zeros(5, dtype=int)
print(w)
print(type(w))
print(w.dtype)

float64
[0 0 0 0 0]
<class 'numpy.ndarray'>
int64


What is not possible, for example, is to add a string value (that is, a value of type `string`) to a `numpy.ndarray` object, because all the elements of the array must be of the same type (or at least of a type that admits conversion) and must also have the same size. To check the size of an array, one may use the `len` function:


In [8]:
print(len(u))
v = np.zeros(10, dtype=int)
print(u + v) # A type conversion from int64 to float64 is performed implicitly
print(u + w) # ERROR: The vectors do not have the same size!

10
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: operands could not be broadcast together with shapes (10,) (5,) 

A more specific way to check the dimension of an array is to use `u.shape`, which returns a tuple with the dimensions of the array:


In [31]:
print(u.shape)

(4,)


`shape` informs us about the size of the array in *each* direction. In the case of arrays viewed as vectors, there is only one direction, whereas in data sets with multiple indices (matrices, or $n$-dimensional tensors), `shape` would tell us the size of these data structures in each direction. For example, to create a zero integer matrix of size $2\times 3$:


In [32]:
A =  np.zeros((2,3), dtype=int)
print(A)
print(A.shape)

[[0 0 0]
 [0 0 0]]
(2, 3)


We can change the entries of an array by indexing,


In [33]:
print(u)
u[0] = 10.0
u[3] = -4.3
u[9] = 1.0
print(u)

[2 3 4 5]


IndexError: index 9 is out of bounds for axis 0 with size 4

> **IMPORTANT NOTE**: Remember that in Python index values start at 0.

Of course, there are other ways to create arrays, such as using the `ones` function to create an array containing only *ones*:


In [46]:
w = np.ones(5)
print(w)
print(w.dtype)

[1. 1. 1. 1. 1.]
float64


or an array of random values:


In [47]:
w = np.random.rand(6)
print(w)

[0.35107745 0.24891981 0.47866285 0.76436662 0.21104532 0.92300589]


or also a `numpy.array` of numbers created from a Python list of numbers:


In [48]:
u = [4.0, 8.0, 9.0, 11.0, -2.0]
v = np.array(u)
print(v)

[ 4.  8.  9. 11. -2.]


There are two other methods for creating arrays of numbers that will be useful throughout the course (and in particular when we have to plot functions with **Matplotlib**):
- `numpy.arange`
- `numpy.linspace`

The `arange` function creates an array with consecutive integer values (in a way similar to Python's `range` function). For example, to create the row vector $\vec{u}=(0, 1, 2, 3, 4, 5)$ using `arange`,


In [49]:
u = np.arange(6)
print(u)
print(type(u))
print(u.dtype)

[0 1 2 3 4 5]
<class 'numpy.ndarray'>
int64


We can check that the number $6$ is not included because the range of values starts at $0$ and the array has only six elements. To change the numerical value at which the array starts:


In [50]:
u = np.arange(2, 6)
print(u)

[2 3 4 5]


The `linspace` function creates an array of equally spaced numbers with an initial and final value (both included) and with a prescribed size:


In [51]:
w = np.linspace(0., 100., 6)
print(w)
print(w.dtype)

[  0.  20.  40.  60.  80. 100.]
float64


This `linspace` function, together with the `meshgrid` function, will be used regularly throughout the course to plot functions with **Matplotlib**.


## Functions and arithmetic with arrays

**NumPy** arrays support the basic arithmetic operations (product, sums, differences, *etc.*):


In [52]:
a = np.array([1.0, 0.2, 1.2])
b = np.array([2.0, 0.1, 2.1])
print(a)
print(b)

# Sum of a and b
c = a + b
print(c)

[1.  0.2 1.2]
[2.  0.1 2.1]
[3.  0.3 3.3]


and the product of all its elements by a scalar value,


In [53]:
c = 10.0*a
print(c)

[10.  2. 12.]


and raising all of its components to a power:


In [54]:
a = np.array([2, 3, 4])
print(a**2)

[ 4  9 16]


The usual mathematical functions can also be applied to each of their components:


In [55]:
# Create the vector [0, π/2, π, 3π/2]
a = np.array([0.0, np.pi/2, np.pi, 3*np.pi/2])
print(a)

# Compute the sine of each component of the vector
b = np.sin(a)
print(b)

[0.         1.57079633 3.14159265 4.71238898]
[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]


The previous code computes the sine of each coefficient of the vector `a`. We should emphasize that the function being used is `np.sin`, which depends directly on the **NumPy** module. Using any other implementation of the function in other modules (for example, in the **Math** module) could lead to an error.

Of course, we could also compute the sine of each coefficient of the vector by accessing each element via its index and carrying out the calculations inside a `for` loop:


In [56]:
b = np.zeros(len(a))
for i in range(len(a)):
    b[i] = np.sin(a[i])

print(b)

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]


In this case the program is longer and harder to read. Moreover, in many cases it will be slower. The manipulation of arrays and any calculations performed on them without accessing their indices are usually known as **vectorization**. Whenever possible, using vectorization will increase the efficiency and speed of computational codes. In the final exercise of these notes, the performance of this type of technique will be analyzed.


## Slicing arrays

When working with arrays of numbers, it is common to need to extract a subset of them to create a new array. For example, taking the first three coefficients of a vector or, in the case of matrices, restricting calculations to the second column. This type of operation is called array slicing.

Let us explore this through several examples, working with an array of random values:


In [57]:
a = np.random.rand(5)
print(a)

# Using ':' means the entire index range, that is, from 0 to (length-1)
b = a[:]
print("Slicing using '[:]' {}".format(b))

# Using '1:3' means indices 1 -> 3 (excluding 3)
b = a[1:3]
print("Slicing using '[1:3]': {}".format(b))

# Using '2:-1' means indices 2 -> the second from the end (excluding it)
b = a[2:-1]
print("Slicing using '[2:-1]': {}".format(b))

# Using '2:-2' means indices 2 -> the third from the end (excluding it)
b = a[2:-2]
print("Slicing using '[2:-2]': {}".format(b))

[0.48168868 0.80420184 0.64609647 0.4100751  0.92354202]
Slicing using '[:]' [0.48168868 0.80420184 0.64609647 0.4100751  0.92354202]
Slicing using '[1:3]': [0.80420184 0.64609647]
Slicing using '[2:-1]': [0.64609647 0.4100751 ]
Slicing using '[2:-2]': [0.64609647]


> **NOTE**: the use of index `-1` corresponds to the last element of the array. Likewise, index `-2` corresponds to the second-to-last element, *etc.*. This convention of referencing indices from the end of an array is very useful, since with these negative indices one can refer to the last coefficients of an array without having to explicitly refer to its size (or even to know it explicitly).


If what we want is to slice an array from the beginning or from the end, we must use the index syntax with '`:`'


In [58]:
# Using ':3' means using indices from the beginning up to 3 (excluding index 3)
b = a[:3]
print("Slicing using '[:3]': {}".format(b))

# Using '4:' means indices from 4 to the end
b = a[4:]
print("Slicing using '[4:]': {}".format(b))

# Using ':' means all indices from the beginning to the end
b = a[:]
print("Slicing using '[:]': {}".format(b))

Slicing using '[:3]': [0.48168868 0.80420184 0.64609647]
Slicing using '[4:]': [0.92354202]
Slicing using '[:]': [0.48168868 0.80420184 0.64609647 0.4100751  0.92354202]


Slicing can also be applied to matrices:


In [59]:
B = np.array([[1.3, 0], [0, 2.0]])
print(B)

# Extract the second row
row = B[1, :]
print(row)

# Extract the first column (stored as a row vector)
col = B[:, 0]
print(col)

[[1.3 0. ]
 [0.  2. ]]
[0. 2.]
[1.3 0. ]


There are many other strategies and syntax forms related to array slicing that are beyond the scope of this brief introduction to **NumPy**. For more detailed information, see: https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html


## Exercise: acceleration with NumPy in the computation of vector norms

The Euclidean norm (or *magnitude*) of a vector $\vec{x}=(x_{0},\ldots,x_{n-1})\in\mathbb{R}^{n}$ is given by

$$
\| x \| = \sqrt{\sum_{i=0}^{n-1} x_{i} x_{i}},
$$

where $x_{i}$ is the $i$-th coefficient of $\vec{x}$. In short, its norm is nothing but the calculation of the inner product of the vector with itself, followed by taking a square root. To compute the norm value one can follow different strategies: the first is to use a loop to go through all the coefficients of the vector and add the square of each coefficient, then take the sum of all these quantities and compute its square root.

To assess the computational performance of this implementation, we will take a moderately large vector (10 million entries) and compute the running time:


In [60]:
# Create a NumPy array with 10 million random values
x = np.random.rand(10000000)
print(type(x))

<class 'numpy.ndarray'>


In [61]:
def compute_norm(x):
    norm = 0.0
    for xi in x:
        norm += xi*xi
    return np.sqrt(norm)

%time norm = compute_norm(x)
print(norm)

CPU times: user 3.05 s, sys: 4.24 ms, total: 3.05 s
Wall time: 3.11 s
1825.2381405346423


The computation time that interests us is the one appearing under the label '`Wall time`'.

> **NOTE**: The details of how the `%time` label works in these notes are not important for this course. We should point out that this way of proceeding is only valid for consoles or files executed under [I]Python and Jupyter server environments. This way of working is very compact and convenient for measuring the time required to complete the execution of a line of code.


**Exercise 1:**
Using the same loop-based implementation, access each element of the vector by its index, starting from the first and going to the last. Do the same with a loop that accesses them in reverse order, from the last to the first.


In [62]:
# WRITE YOUR CODE HERE


**Exercise 2:**
Try to use **NumPy** functions to define a function that avoids looping over the coefficients of the vector and does not access it element by element (that is, make a vectorized version of the computation of the Euclidean norm).


In [63]:
# WRITE YOUR CODE HERE


**Exercise 3:**
Compare the computation times of the four implementations for different dimensions of the vector $\vec{x}$, of sizes $10$, $10^3$, $10^5$, $10^7$. From these computation times, what conclusion can be drawn?


In [64]:
# WRITE YOUR CODE HERE
